export const fr: Record<string, string> = {
  'Skip to content': 'Aller au contenu',
  'Select all remaining products for the final payment.': 'Sélectionnez tous les produits restants pour le dernier paiement.',
  'Auto-lock': 'Verrouillage auto',
  '5 minutes': '5 minutes',
  '10 minutes': '10 minutes',
  '15 minutes': '15 minutes',
  '30 minutes': '30 minutes',
  'Never': 'Jamais',
  'Auto-lock duration is invalid.': 'Le délai de verrouillage est invalide.',
  'Preferences and terminal controls': 'Préférences et commandes du terminal',
  'Printer address': 'Adresse de l’imprimante',
  '12 hour': '12 heures',
  '24 hour': '24 heures',
  'Add': 'Ajouter',
  'Add category': 'Ajouter une catégorie',
  'Add compensation': 'Ajouter une rémunération',
  'Add costs': 'Ajouter des coûts',
  'Add expense': 'Ajouter une dépense',
  'Add ingredient': 'Ajouter un ingrédient',
  'Add monthly pay': 'Ajouter un salaire',
  'Add product': 'Ajouter un produit',
  'Add product photo': 'Ajouter une photo',
  'Add size': 'Ajouter une taille',
  'Add staff': 'Ajouter un équipier',
  'Add to order': 'Ajouter',
  'Add {name}': 'Ajouter {name}',
  'Adding…': 'Ajout…',
  'Adjust count': 'Ajuster',
  'All': 'Tout',
  'All active ingredients are above their thresholds.':
    'Tous les ingrédients actifs sont au-dessus de leur seuil.',
  'All availability': 'Toutes disponibilités',
  'All products': 'Tous les produits',
  'All sizes': 'Toutes les tailles',
  'All stock levels': 'Tous les niveaux',
  'All units': 'Toutes les unités',
  'Amount': 'Montant',
  'Amount given': 'Montant reçu',
  'Application': 'Application',
  'Artwork': 'Visuel',
  'At least': 'Au moins',
  'At most': 'Au plus',
  'Availability': 'Disponibilité',
  'Available': 'Disponible',
  'Average': 'Moyenne',
  'Average order': 'Ticket moyen',
  'Base price': 'Prix de base',
  'Base unit': 'Unité de base',
  'By category': 'Par catégorie',
  'By size': 'Par taille',
  'Calendar': 'Calendrier',
  'Cancel': 'Annuler',
  'Cancel order': 'Annuler la commande',
  'Cancelled': 'Annulée',
  'Cancelling…': 'Annulation…',
  'Card': 'Carte',
  'Card · exact amount': 'Carte · montant exact',
  'Cart': 'Panier',
  'Carton': 'Carton',
  'Cash': 'Espèces',
  'Cashier': 'Caissier',
  'Categories': 'Catégories',
  'Category': 'Catégorie',
  'Category name': 'Nom de la catégorie',
  'Category save failed.': 'La catégorie n’a pas pu être enregistrée.',
  'Change': 'Monnaie',
  'Change PIN': 'Changer le code',
  'Change PIN for {name}': 'Changer le code de {name}',
  'Change product photo': 'Changer la photo',
  'Changes saved.': 'Modifications enregistrées.',
  'Check for update': 'Rechercher une mise à jour',
  'Checking connection…': 'Vérification de la connexion…',
  'Checking…': 'Vérification…',
  'Choice': 'Choix',
  'Choice delete failed.': 'Le choix n’a pas pu être supprimé.',
  'Choice name': 'Nom du choix',
  'Choice section save failed.': 'Les choix n’ont pas pu être enregistrés.',
  'Choices': 'Choix',
  'CHOICES': 'CHOIX',
  'Choose a live menu record or add a new product.':
    'Choisissez un produit du menu ou ajoutez-en un.',
  'Choose a live stock record to review its balance and movements.':
    'Choisissez un ingrédient pour voir le stock et les mouvements.',
  'Choose a saved order to inspect its receipt snapshot.':
    'Choisissez une commande pour voir son ticket.',
  'Choose a staff member and enter a six-digit PIN.':
    'Choisissez un équipier et saisissez un code à six chiffres.',
  'Choose product': 'Choisir un produit',
  'Clear cart': 'Vider',
  'Clear filters': 'Effacer les filtres',
  'Clear search': 'Effacer la recherche',
  'Clock': 'Horloge',
  'Close cancellation': 'Fermer l’annulation',
  'Close category editor': 'Fermer la catégorie',
  'Close choices editor': 'Fermer les choix',
  'Close compensation': 'Fermer la rémunération',
  'Close expense': 'Fermer la dépense',
  'Close ingredient editor': 'Fermer l’ingrédient',
  'Close movement history': 'Fermer l’historique',
  'Close payment': 'Fermer le paiement',
  'Close PIN form': 'Fermer le formulaire du code',
  'Close product editor': 'Fermer le produit',
  'Close purchase receipt': 'Fermer la réception',
  'Close recipe editor': 'Fermer la recette',
  'Close selection': 'Fermer la sélection',
  'Close sizes editor': 'Fermer les tailles',
  'Close staff form': 'Fermer le formulaire',
  'Close stock adjustment': 'Fermer l’ajustement',
  'Cloud synced': 'Synchronisée',
  'Completed': 'Terminée',
  'Confirm PIN': 'Confirmer le code',
  'Connection': 'Connexion',
  'Copy': 'Copier',
  'Copy choices from another product': 'Copier les choix d’un autre produit',
  'Copy failed.': 'La copie a échoué.',
  'Copy from product': 'Copier depuis un produit',
  'Correct': 'Corriger',
  'Correction reason must contain 3 to 240 characters.':
    'Le motif doit contenir entre 3 et 240 caractères.',
  'Correct expense': 'Corriger la dépense',
  'Could not use that photo.': 'Cette photo n’a pas pu être utilisée.',
  'That photo has no visible product.': 'Cette photo ne contient aucun produit visible.',
  'Count, spoilage or breakage': 'Inventaire, casse ou perte',
  'Counted on hand': 'Quantité comptée',
  'Created': 'Créée',
  'Critical': 'Critique',
  'Current order': 'Commande en cours',
  'Custom': 'Autre',
  'CUSTOMIZE ORDER': 'PERSONNALISER',
  'Daily average': 'Moyenne quotidienne',
  'Daily net sales': 'Ventes nettes par jour',
  'Daily net sales for the latest 12 days': 'Ventes nettes des 12 derniers jours',
  'Daily saved totals': 'Totaux enregistrés du jour',
  'Dashboard': 'Tableau',
  'Date': 'Date',
  'DATE': 'DATE',
  'Default': 'Par défaut',
  'Decrease {name} quantity': 'Diminuer {name}',
  'Delete': 'Supprimer',
  'Delete failed.': 'La suppression a échoué.',
  'Delete {name}': 'Supprimer {name}',
  'Delete {name}? Drinks using it will need updating.':
    'Supprimer {name} ? Les boissons concernées devront être mises à jour.',
  'Delete {name}? Its products will remain uncategorized.':
    'Supprimer {name} ? Ses produits resteront sans catégorie.',
  'Delete {name}? Past orders will be preserved.':
    'Supprimer {name} ? Les commandes passées seront conservées.',
  'Delete {name}? Past records will be preserved.':
    'Supprimer {name} ? L’historique sera conservé.',
  'Delete this monthly pay?': 'Supprimer ce salaire mensuel ?',
  'Delivery or transfer': 'Livraison ou transfert',
  'Description': 'Description',
  'DIFFERENCE': 'ÉCART',
  'Dine in': 'Sur place',
  'Dine In': 'Sur place',
  'Does this order need to be split?': 'Cette commande doit-elle être payée séparément ?',
  'Edit product': 'Modifier le produit',
  'Ends (optional)': 'Fin (facultatif)',
  'English': 'English',
  'Every gram.': 'Chaque gramme.',
  'Every sale.': 'Chaque vente.',
  'Exact saved balance': 'Solde enregistré',
  'Expense could not be saved.': 'La dépense n’a pas pu être enregistrée.',
  'Expenses': 'Dépenses',
  'Extra': 'Supplément',
  'Filter availability': 'Filtrer la disponibilité',
  'Filter stock level': 'Filtrer le niveau',
  'Filter stock unit group': 'Filtrer l’unité',
  'Finish or clear the open order before installing.':
    'Terminez ou videz la commande en cours avant d’installer.',
  'Fiche technique not added': 'Fiche technique manquante',
  'Generated on save': 'Généré à l’enregistrement',
  'Given': 'Reçu',
  'Gross profit': 'Marge brute',
  'Group': 'Groupe',
  'Groups': 'Groupes',
  'Healthy': 'Suffisant',
  'How many choices': 'Nombre de choix',
  'IPv4 address and port': 'Adresse IPv4 et port',
  'Included': 'Inclus',
  'Increase {name} quantity': 'Augmenter {name}',
  'INGREDIENT': 'INGRÉDIENT',
  'Ingredient': 'Ingrédient',
  'Ingredient {name}': 'Ingrédient {name}',
  'Ingredient cost': 'Coût ingrédients',
  'Ingredient cost incomplete': 'Coût ingrédients incomplet',
  'Ingredient name': 'Nom de l’ingrédient',
  'Ingredient save failed.': 'L’ingrédient n’a pas pu être enregistré.',
  'Ingredient usage': 'Utilisation des ingrédients',
  'Recipe deductions': 'Déductions de recettes',
  'INGREDIENT TYPES USED': 'TYPES D’INGRÉDIENTS UTILISÉS',
  'INGREDIENTS USED': 'INGRÉDIENTS UTILISÉS',
  'Ingredients below their threshold': 'Ingrédients sous le seuil',
  'Inventory': 'Inventaire',
  'Items': 'Articles',
  'ITEMS': 'ARTICLES',
  'Items sold': 'Articles vendus',
  'Keep order': 'Conserver',
  'Language, printer, sync, and updates':
    'Langue, imprimante, synchronisation et mises à jour',
  'Last month': 'Mois dernier',
  'Last successful sync': 'Dernière synchro réussie',
  'Last week': 'Sem. dernière',
  'Later': 'Plus tard',
  'Latest activity from the counter': 'Dernière activité au comptoir',
  'Link exact base-unit quantities when ready.':
    'Indiquez les quantités exactes quand la recette est prête.',
  'Linked': 'Lié',
  'Liquids': 'Liquides',
  'Loading': 'Chargement',
  'Loading current stock…': 'Chargement du stock…',
  'Loading live menu…': 'Chargement du menu…',
  'Loading live stock…': 'Chargement du stock…',
  'Loading movements…': 'Chargement des mouvements…',
  'Loading Olaso': 'Chargement d’Olaso',
  'Loading order history…': 'Chargement des commandes…',
  'Loading recent orders…': 'Chargement des commandes récentes…',
  'Loading sales…': 'Chargement des ventes…',
  'Loading saved costs…': 'Chargement des coûts…',
  'Loading saved summary': 'Chargement du résumé',
  'Loading staff…': 'Chargement de l’équipe…',
  'Loading the saved menu…': 'Chargement du menu enregistré…',
  'Loading…': 'Chargement…',
  'Lock / switch staff': 'Verrouiller / changer',
  'Lock terminal': 'Verrouiller le terminal',
  'Locking…': 'Verrouillage…',
  'Low': 'Bas',
  'Low stock': 'Stock bas',
  'Low-stock threshold': 'Seuil de stock bas',
  'MAD': 'MAD',
  'Manage {name}': 'Gérer {name}',
  'Manager': 'Manager',
  'Map size': 'Par taille',
  'Mark {name} Offert': 'Marquer {name} offert',
  'MENU GROUP': 'GROUPE',
  'MENU ITEM': 'PRODUIT',
  'MINIMUM': 'MINIMUM',
  'Month': 'Mois',
  'Monthly amount': 'Montant mensuel',
  'Monthly pay': 'Salaire mensuel',
  'Mixed': 'Mixte',
  'Movement history': 'Historique des mouvements',
  'Name': 'Nom',
  'Need': 'Reste',
  'Needs attention': 'À surveiller',
  'Needs sync': 'À synchroniser',
  'NET SALES': 'VENTES NETTES',
  'Net sales trend': 'Tendance des ventes nettes',
  'New group': 'Nouveau groupe',
  'New product': 'Nouveau produit',
  'New six-digit PIN': 'Nouveau code à six chiffres',
  'Next month': 'Mois suivant',
  'Next page': 'Page suivante',
  'Next product page': 'Page produits suivante',
  'Next stock page': 'Page stock suivante',
  'No category sales.': 'Aucune vente par catégorie.',
  'No comparison yet': 'Pas encore de comparaison',
  'No expenses saved.': 'Aucune dépense enregistrée.',
  'No ingredients match these filters.': 'Aucun ingrédient ne correspond.',
  'No matching orders.': 'Aucune commande correspondante.',
  'No monthly pay saved.': 'Aucun salaire enregistré.',
  'No movements recorded.': 'Aucun mouvement enregistré.',
  'No order selected': 'Aucune commande sélectionnée',
  'No prior period': 'Pas de période précédente',
  'No product sales.': 'Aucune vente produit.',
  'No profile sales.': 'Aucune vente par profil.',
  'No products match these filters.': 'Aucun produit ne correspond.',
  'No products match this category and search.':
    'Aucun produit ne correspond à cette catégorie et cette recherche.',
  'No recipe usage.': 'Aucune utilisation de recette.',
  'No, one payment': 'Non, un seul paiement',
  'No saved activity in this period': 'Aucune activité enregistrée sur cette période',
  'No saved orders yet.': 'Aucune commande enregistrée.',
  'No sales in period': 'Aucune vente sur la période',
  'No sales yet': 'Pas encore de ventes',
  'No update available.': 'Aucune mise à jour disponible.',
  'Not linked': 'Non lié',
  'Not yet': 'Pas encore',
  'Note (optional)': 'Note (facultatif)',
  'Nothing left.': 'Rien à encaisser.',
  'Off': 'Off',
  'Offert': 'Offert',
  'Offline': 'Hors ligne',
  'Olaso': 'Olaso',
  'OLASO': 'OLASO',
  'Olaso operations dashboard': 'Tableau de bord Olaso',
  'Olaso orders': 'Commandes Olaso',
  'Olaso point of sale': 'Caisse Olaso',
  'Olaso POS': 'Olaso POS',
  'Olaso products': 'Produits Olaso',
  'Olaso reports': 'Rapports Olaso',
  'Olaso stock': 'Stock Olaso',
  'Olaso terminal': 'Terminal Olaso',
  'On': 'On',
  'ON HAND': 'EN STOCK',
  'On hand': 'En stock',
  'One time': 'Ponctuel',
  'Online': 'En ligne',
  'Open': 'Ouvert',
  'Open staff menu': 'Ouvrir le menu profil',
  'Opening quantity': 'Quantité d’ouverture',
  'Operating profit': 'Résultat d’exploitation',
  'Optional': 'Facultatif',
  'Order': 'Commande',
  'ORDER': 'COMMANDE',
  'Order items': 'Articles',
  'Order online': 'En ligne',
  'Order status': 'Statut',
  'Orders': 'Commandes',
  'Orders pagination': 'Pages des commandes',
  'Out': 'Rupture',
  'Owner': 'Propriétaire',
  'PACKAGE RECEIPT': 'RÉCEPTION',
  'Package label': 'Libellé du colis',
  'Packages': 'Colis',
  'Paid on': 'Payé le',
  'Payment': 'Paiement',
  'PAYMENT': 'PAIEMENT',
  'Payment Details': 'Détail du paiement',
  'Payment method': 'Mode de paiement',
  'People who can use this tablet': 'Personnes autorisées sur cette tablette',
  'Period total': 'Total de la période',
  'PHYSICAL COUNT': 'INVENTAIRE',
  'Pieces': 'Pièces',
  'PIN': 'Code',
  'PIN changed.': 'Code modifié.',
  'PIN could not be changed.': 'Le code n’a pas pu être modifié.',
  'Place order': 'Encaisser',
  'Place Order': 'Encaisser',
  'POS': 'Caisse',
  'POS availability': 'Disponible en caisse',
  'Previous month': 'Mois précédent',
  'Previous page': 'Page précédente',
  'Previous product page': 'Page produits précédente',
  'Previous stock page': 'Page stock précédente',
  'Price': 'Prix',
  'PRICE': 'PRIX',
  'Price in MAD': 'Prix en MAD',
  'Price paid': 'Prix payé',
  'Price per package': 'Prix par colis',
  'Primary navigation': 'Navigation principale',
  'Print the immutable saved receipt': 'Imprimer le ticket enregistré',
  'Printer': 'Imprimante',
  'Printer unavailable': 'Imprimante indisponible',
  'Printing…': 'Impression…',
  'PRODUCT': 'PRODUIT',
  'Product': 'Produit',
  'Product categories': 'Catégories',
  'Product code': 'Code produit',
  'Product could not be deleted.': 'Le produit n’a pas pu être supprimé.',
  'Product information': 'Fiche produit',
  'Product menu': 'Carte',
  'Product name': 'Nom du produit',
  'PRODUCT SIZES': 'TAILLES',
  'Product save failed.': 'Le produit n’a pas pu être enregistré.',
  'Products': 'Produits',
  'Products pagination': 'Pages des produits',
  'Profit': 'Bénéfice',
  'Profile performance': 'Performance par profil',
  'Purchase could not be saved.': 'L’achat n’a pas pu être enregistré.',
  'Quantities stay as whole': 'Les quantités restent entières',
  'Quantity per package': 'Quantité par colis',
  'Quantity received': 'Quantité reçue',
  'Quick add best sellers': 'Ajout rapide des meilleures ventes',
  'Quick amounts': 'Montants rapides',
  'Quick period': 'Période rapide',
  'Ready': 'Prêt',
  'Reason': 'Motif',
  'Receipt pending': 'Ticket en attente',
  'Receipts': 'Tickets',
  'Receive': 'Réceptionner',
  'Receive purchase': 'Réceptionner l’achat',
  'Receive stock': 'Réceptionner du stock',
  'Recent movements': 'Mouvements récents',
  'Recent orders': 'Commandes récentes',
  'Recent orders are unavailable. Select Retry summary.': 'Commandes récentes indisponibles. Sélectionnez « Réessayer le résumé ».',
  'Recently updated': 'Récemment modifié',
  'RECIPE': 'RECETTE',
  'Recipe & stock': 'Recette et stock',
  'Recipe save failed.': 'La recette n’a pas pu être enregistrée.',
  'Remaining': 'Reste',
  'Remove': 'Retirer',
  'Remove {name}': 'Retirer {name}',
  'Remove Offert from {name}': 'Retirer l’offert de {name}',
  'Remove stock change': 'Retirer l’effet stock',
  'Rename': 'Renommer',
  'Rent': 'Loyer',
  'Repeats': 'Récurrence',
  'Replace': 'Remplacer',
  'Replacement': 'Remplacement',
  'Report': 'Rapport',
  'Report type': 'Type de rapport',
  'Reports': 'Rapports',
  'Required': 'Obligatoire',
  'Required · pick one': 'Obligatoire · en choisir un',
  'Required reason': 'Motif obligatoire',
  'Retry': 'Réessayer',
  'Retry summary': 'Réessayer le résumé',
  'Retry terminal check': 'Réessayer',
  'Reversal': 'Contrepassation',
  'Role': 'Rôle',
  'SALES': 'VENTES',
  'Sales': 'Ventes',
  'Sales rhythm': 'Rythme des ventes',
  'Sales, products, stock, and costs': 'Ventes, produits, stock et coûts',
  'Save': 'Enregistrer',
  'Save category': 'Enregistrer la catégorie',
  'Save changes': 'Enregistrer',
  'Save compensation': 'Enregistrer la rémunération',
  'Save correction': 'Enregistrer la correction',
  'Save count': 'Enregistrer le comptage',
  'Save expense': 'Enregistrer la dépense',
  'Save failed.': 'Enregistrement impossible.',
  'Save purchase': 'Enregistrer l’achat',
  'Save sizes': 'Enregistrer les tailles',
  'Save the product, then add a size before it can be sold.':
    'Enregistrez le produit, puis ajoutez une taille avant de le vendre.',
  'Saving appends one movement and updates the balance atomically.':
    'L’enregistrement ajoute un mouvement et met à jour le solde.',
  'Saving this order on the tablet…': 'Enregistrement de la commande sur la tablette…',
  'Saving…': 'Enregistrement…',
  'Search ingredients or packaging': 'Rechercher un ingrédient',
  'Search order': 'Rechercher une commande',
  'Search orders': 'Rechercher des commandes',
  'Search product': 'Rechercher un produit',
  'Search products': 'Rechercher des produits',
  'Search stock': 'Rechercher dans le stock',
  'Select': 'Choisir',
  'Select a product': 'Sélectionnez un produit',
  'Select an ingredient': 'Sélectionnez un ingrédient',
  'Select products.': 'Sélectionnez des produits.',
  'Select staff': 'Choisir un équipier',
  'SELECTED ORDER': 'COMMANDE',
  'Selected sizes only': 'Tailles sélectionnées seulement',
  'Service': 'Service',
  'SERVICE': 'SERVICE',
  'Service type': 'Type de service',
  'Set amount': 'Fixer la quantité',
  'Set up': 'Configurer',
  'Settings': 'Paramètres',
  'Settings saved on this tablet.': 'Paramètres enregistrés sur cette tablette.',
  'Share of period sales': 'Part des ventes de la période',
  'Showing {from} to {to} of {total} orders':
    'Affichage de {from} à {to} sur {total} commandes',
  'Six-digit PIN': 'Code à six chiffres',
  'Size': 'Taille',
  'Size delete failed.': 'La taille n’a pas pu être supprimée.',
  'Size name': 'Nom de la taille',
  'Size save failed.': 'La taille n’a pas pu être enregistrée.',
  'Sizes': 'Tailles',
  'Sizes & options': 'Tailles et options',
  'Slide to place order, {amount}': 'Glisser pour encaisser, {amount}',
  'Slide to place order…': 'Glisser pour encaisser…',
  'Some sales are missing ingredient cost.':
    'Certaines ventes n’ont pas de coût ingrédients.',
  'Sort order': 'Ordre',
  'Sort products': 'Trier les produits',
  'Split': 'Partager',
  'Split by days': 'Réparti sur les jours',
  'Split by month days': 'Réparti sur les jours du mois',
  'Staff': 'Équipe',
  'Staff & access': 'Équipe et accès',
  'Staff access is unavailable. Connect and sync this terminal.':
    'L’accès équipe est indisponible. Connectez et synchronisez ce terminal.',
  'Staff access is unavailable. Sign in again.':
    'L’accès équipe est indisponible. Reconnectez-vous.',
  'Staff member': 'Équipier',
  'Staff member could not be added.': 'L’équipier n’a pas pu être ajouté.',
  'Staff session is unavailable. Lock and sign in again.':
    'La session est indisponible. Verrouillez et reconnectez-vous.',
  'Staff session is unavailable. Sign in again.':
    'La session est indisponible. Reconnectez-vous.',
  'Starting…': 'Démarrage…',
  'Starts': 'Début',
  'STATUS': 'STATUT',
  'Stock': 'Stock',
  'STOCK ADDITION': 'ENTRÉE DE STOCK',
  'Stock adjustment failed.': 'L’ajustement n’a pas pu être enregistré.',
  'Stock change': 'Effet stock',
  'Stock inventory': 'Inventaire',
  'Stock level': 'Niveau de stock',
  'Stock pagination': 'Pages du stock',
  'STOCK RECIPE': 'RECETTE',
  'STOCK RECORD': 'FICHE STOCK',
  'Stock received': 'Stock réceptionné',
  'Stock usage': 'Consommation',
  'Stop': 'Arrêter',
  'Stop this monthly pay from today?': 'Arrêter cette rémunération à partir d’aujourd’hui ?',
  'Stock value': 'Valeur du stock',
  'Stock warnings are unavailable. Select Retry summary.': 'Alertes stock indisponibles. Sélectionnez « Réessayer le résumé ».',
  'Subtotal': 'Sous-total',
  'Summary unavailable': 'Résumé indisponible',
  'Supplier (optional)': 'Fournisseur (facultatif)',
  'Switch staff? The current order will stay for the next staff member.':
    'Changer d’équipier ? La commande en cours restera pour la personne suivante.',
  'Sync': 'Synchronisation',
  'Sync now': 'Synchroniser',
  'Synced': 'Synchronisée',
  'Syncing…': 'Synchronisation…',
  'Take away': 'À emporter',
  'Take Away': 'À emporter',
  'Take payment': 'Encaisser',
  'Tap another day for a period.': 'Touchez un autre jour pour une période.',
  'Tap to add': 'Toucher pour ajouter',
  'Tap to return': 'Toucher pour retirer',
  'Terminal locked': 'Terminal verrouillé',
  'Terminal offline': 'Terminal hors ligne',
  'Terminal online': 'Terminal en ligne',
  'Terminal recovery': 'Récupération du terminal',
  'Terminal settings are unavailable. POS remains locked.':
    'Les paramètres du terminal sont indisponibles. La caisse reste verrouillée.',
  'Terminal settings could not be verified. POS remains locked. Retry or restore this terminal before serving orders.':
    'Les paramètres du terminal n’ont pas pu être vérifiés. La caisse reste verrouillée. Réessayez ou restaurez ce terminal avant de servir.',
  'Test printer': 'Tester l’imprimante',
  'Testing…': 'Test…',
  'The correction could not be saved.': 'La correction n’a pas pu être enregistrée.',
  'The correction date cannot be before the original expense start date.':
    'La date de correction ne peut pas être antérieure à la date de début de la dépense initiale.',
  'The order could not be saved.': 'La commande n’a pas pu être enregistrée.',
  'The original order stays in history and the saved stock is restored. Olaso does not refund or reverse card payments.':
    'La commande d’origine reste dans l’historique et le stock est rétabli. Olaso ne rembourse pas les paiements par carte et n’effectue aucune contrepassation bancaire.',
  'The terminal could not be locked.': 'Le terminal n’a pas pu être verrouillé.',
  'Language could not be changed. Select EN or FR to try again.': 'La langue n’a pas pu être modifiée. Sélectionnez EN ou FR pour réessayer.',
  'This month': 'Ce mois',
  'This payment': 'Ce règlement',
  'This period': 'Cette période',
  'This staff identity is unavailable offline. Connect and sync this terminal.':
    'Cette identité n’est pas disponible hors ligne. Connectez et synchronisez ce terminal.',
  'This week': 'Cette sem.',
  'Today': 'Aujourd’hui',
  'TODAY’S BEST SELLER': 'MEILLEURE VENTE DU JOUR',
  'Today’s pulse': 'Le rythme du jour',
  'Today’s sales summary': 'Résumé des ventes du jour',
  'Too many failed PIN attempts. Try again later.':
    'Trop d’essais de code. Réessayez plus tard.',
  'Total': 'Total',
  'TOTAL': 'TOTAL',
  'Track every sale from counter to completion':
    'Suivez chaque vente, du comptoir jusqu’à l’encaissement',
  'Unable to unlock. Check the connection and try again.':
    'Déverrouillage impossible. Vérifiez la connexion et réessayez.',
  'Unavailable': 'Indisponible',
  'Uncategorized': 'Sans catégorie',
  'Unattributed': 'Non attribué',
  'UNIT GROUP': 'FAMILLE',
  'Units and share of sales': 'Unités et part des ventes',
  'UNITS SOLD': 'UNITÉS VENDUES',
  'Units sold trend': 'Tendance des unités vendues',
  'Unknown actor': 'Auteur inconnu',
  'Unlock': 'Déverrouiller',
  'Unlock Olaso': 'Déverrouiller Olaso',
  'Unlocking…': 'Déverrouillage…',
  'Up to 8 saved sizes': 'Jusqu’à 8 tailles',
  'Update': 'Mise à jour',
  'Update to {version}': 'Mettre à jour vers {version}',
  'Updated after every saved movement': 'Mis à jour à chaque mouvement',
  'USED TODAY': 'UTILISÉ AUJOURD’HUI',
  'Used ingredients': 'Ingrédients utilisés',
  'Usual': 'Habituel',
  'View all': 'Tout voir',
  'Wages': 'Salaires',
  'Wages and monthly bills are split across the days in each month. One-time costs count on the day they were recorded.':
    'Les salaires et charges mensuelles sont répartis sur les jours du mois. Les dépenses ponctuelles comptent le jour d’enregistrement.',
  'Waiting sales': 'Ventes en attente',
  'Waiting to sync': 'En attente de synchro',
  'Weighed': 'Pesés',
  'Wrong PIN. Try again.': 'Code incorrect. Réessayez.',
  'Yesterday': 'Hier',
  'Yes, split it': 'Oui, la séparer',
  'Your Olaso terminal is locked and ready for the next shift.':
    'Votre terminal Olaso est verrouillé et prêt pour le prochain service.',
  'local service ready': 'service local prêt',
  'reprint available': 'réimpression possible',
  'sales stay saved on this tablet.': 'les ventes restent enregistrées sur cette tablette.',
  'Active': 'Actif',
  'Archived': 'Archivé',
  'APPEND-ONLY RECORD': 'HISTORIQUE',
  'Compensation could not be saved.': 'La rémunération n’a pas pu être enregistrée.',
  'Category could not be deleted.': 'La catégorie n’a pas pu être supprimée.',
  'Ingredient could not be deleted.': 'L’ingrédient n’a pas pu être supprimé.',
  'Some saved changes still need synchronization. Use Sync again.':
    'Certaines modifications doivent encore être synchronisées. Relancez la synchronisation.',
  'Staff member changed. Refresh before changing the PIN.':
    'Le profil a changé. Actualisez avant de modifier le code PIN.',
  'Menu and synchronization state are up to date.':
    'Le menu et la synchronisation sont à jour.',
  'Synchronization failed. Try again.':
    'La synchronisation a échoué. Réessayez.',
  'Reprint': 'Réimprimer',
  'Reprint unavailable on this tablet': 'Réimpression indisponible sur cette tablette',
  'Costs': 'Coûts',
  'Français': 'Français',
  'Local settings could not be loaded.':
    'Les paramètres locaux n’ont pas pu être chargés.',
  'Settings were not saved.': 'Les paramètres n’ont pas pu être enregistrés.',
  'Check for an update before installing.':
    'Recherchez une mise à jour avant d’installer.',
  'Update postponed. You can check again later.':
    'Mise à jour reportée. Vous pourrez la rechercher plus tard.',
  'Update installation could not start.':
    'L’installation n’a pas pu démarrer.',
  'Android will ask you to confirm the update. The app restarts after installation.':
    'Android vous demandera de confirmer. L’application redémarre après l’installation.',
  '1 saved order still needs synchronization.':
    '1 commande enregistrée reste à synchroniser.',
  '{count} saved orders still need synchronization.':
    '{count} commandes enregistrées restent à synchroniser.',
  '1 saved order and the menu synchronized.':
    '1 commande et le menu ont été synchronisés.',
  '{count} saved orders and the menu synchronized.':
    '{count} commandes et le menu ont été synchronisés.',
  'Test data sent ({bytes} bytes in {ms} ms). Confirm paper.':
    'Données de test envoyées ({bytes} octets en {ms} ms). Vérifiez le papier.',
  'Version {version} is ready to install.':
    'La version {version} est prête à installer.',
  'Terminal offline · local service ready':
    'Terminal hors ligne · service local prêt',
  'Saved staff is unavailable on this tablet.':
    'L’équipe enregistrée est indisponible sur cette tablette.',
  'Staff member added on this tablet.':
    'Équipier ajouté sur cette tablette.',
  'Staff member deleted.': 'Équipier supprimé.',
  'Staff member could not be deleted.':
    'L’équipier n’a pas pu être supprimé.',
  'up to {max}': 'jusqu’à {max}',
  '{count} items': '{count} articles',
  '{orders} orders · {items} items': '{orders} commandes · {items} articles',
  '{name} quantity: {quantity}': '{name} : {quantity}',
  'Offline · sales stay saved on this tablet.':
    'Hors ligne · les ventes restent enregistrées sur cette tablette.',
  'Sale saved. Receipt remains pending.':
    'Vente enregistrée. Ticket en attente d’impression.',
  'Sale saved. Sending receipt…': 'Vente enregistrée. Envoi du ticket…',
  'Sale saved. Receipt sent; confirm paper.':
    'Vente enregistrée. Ticket envoyé ; vérifiez le papier.',
  'Sale saved.': 'Vente enregistrée.',
  'Reprint remains available.': 'La réimpression reste possible.',
  'Add a product to begin.': 'Ajoutez un produit pour commencer.',
  'The order contains an invalid product or quantity.':
    'La commande contient un produit ou une quantité invalide.',
  'Ready to place the order.': 'Prêt à encaisser.',
  'The order is saved locally. Menu refresh failed.':
    'La commande est enregistrée. Le menu n’a pas pu être actualisé.',
  'The order is saved locally and waiting to synchronize.':
    'La commande est enregistrée et en attente de synchronisation.',
  'Receipt sent; confirm paper.': 'Ticket envoyé ; vérifiez le papier.',
  'Last sync {time}': 'Dernière synchro {time}',
  '{count} orders': '{count} commandes',
  'Page {n}': 'Page {n}',
  'Page {number}': 'Page {number}',
  'Page {page}': 'Page {page}',
  'Completed · Synced': 'Terminée · Synchronisée',
  'Receipt sent · {count} attempt': 'Ticket envoyé · {count} essai',
  'Receipt sent · {count} attempts': 'Ticket envoyé · {count} essais',
  'item': 'article',
  'items': 'articles',
  'Given {n}': 'Reçu {n}',
  'Change {n}': 'Monnaie {n}',
  'Cancel {receiptNumber}': 'Annuler {receiptNumber}',
  '{qty} left': '{qty} restant',
  '{pct}% up vs yesterday': '{pct} % de plus qu’hier',
  '{pct}% down vs yesterday': '{pct} % de moins qu’hier',
  'Saved · {date}': 'Enregistré · {date}',
  'Peak {date}': 'Pic {date}',
  '{count} sold': '{count} vendus',
  '1 choice': '1 choix',
  '{count} choices': '{count} choix',
  '1 immutable version saved.': '1 version enregistrée.',
  '{count} immutable versions saved.': '{count} versions enregistrées.',
  '1 linked ingredient': '1 ingrédient lié',
  '{count} linked ingredients': '{count} ingrédients liés',
  '1 menu group': '1 groupe',
  '{count} menu groups': '{count} groupes',
  '1 product': '1 produit',
  '{count} products': '{count} produits',
  'AVAILABILITY': 'DISPONIBILITÉ',
  'DH': 'DH',
  'Edit': 'Modifier',
  'Edit {name}': 'Modifier {name}',
  'Ingredient cost {amount}': 'Coût ingrédients {amount}',
  'Ingredient cost {min}–{max}': 'Coût ingrédients {min}–{max}',
  'NEW': 'NOUVEAU',
  'One': 'Un',
  'Several': 'Plusieurs',
  'Showing {shown} of {total} live record':
    'Affichage de {shown} sur {total} fiche',
  'Showing {shown} of {total} live records':
    'Affichage de {shown} sur {total} fiches',
  'Sizes · {name}': 'Tailles · {name}',
  'Version {number}': 'Version {number}',
  '{name} amount': 'Quantité {name}',
  '{name} extra': '{name} en plus',
  'Adds {quantity} · purchase cash {amount}':
    'Ajoute {quantity} · achat {amount}',
  'Cancellation reversal': 'Annulation de vente',
  'Count adjustment': 'Ajustement d’inventaire',
  'Current: {quantity}': 'Actuel : {quantity}',
  'Daily average {value}': 'Moyenne quotidienne {value}',
  'Grams': 'Grammes',
  'Milligrams': 'Milligrammes',
  'Millilitres': 'Millilitres',
  'On hand {quantity}': 'En stock {quantity}',
  'Opening balance': 'Stock d’ouverture',
  'Other expenses': 'Autres dépenses',
  'Peak {when} · {amount}': 'Pic {when} · {amount}',
  'Purchase correction reversal': 'Annulation d’achat',
  'Purchase received': 'Achat réceptionné',
  'Quantities stay as whole {unit}. If the shelf already has stock, enter quantity and what you paid. Leave quantity at 0 when the shelf is empty. Base units cannot change after creation.':
    'Les quantités restent entières ({unit}). Si le rayon a déjà du stock, saisissez la quantité et le prix payé. Laissez 0 si le rayon est vide. L’unité de base ne peut plus changer.',
  'Sale deduction': 'Déduction de vente',
  'Saved costs are unavailable.': 'Les coûts enregistrés sont indisponibles.',
  '{title} by day': '{title} par jour',
  'onward': 'et suivants',
};
