/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: Olasotheme-theme.ts
 * Command: astryx theme build Olasotheme-theme.ts
 * Generated: 2026-07-28T15:23:10.129Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const OlasothemeTheme: DefinedTheme;
