import { FloppyDisk, Plus, Trash, X } from '@phosphor-icons/react';
import { useEffect, useState } from 'react';
import type { ManagedChoiceEffect, ManagedChoiceSection, ManagedIngredient, ManagedProduct, ManagedProductSize } from '../../productManagementTypes';
import styles from './ProductChoiceSectionDialog.module.css';

interface ProductChoiceSectionDialogProps {
  product: ManagedProduct;
  products: ManagedProduct[];
  sizes: ManagedProductSize[];
  ingredients: ManagedIngredient[];
  sections: ManagedChoiceSection[];
  onClose: () => void;
  onSave: (section: ManagedChoiceSection) => Promise<unknown>;
  onDelete: (section: Required<Pick<ManagedChoiceSection, 'id' | 'revision'>>) => Promise<unknown>;
  onCopy: (sourceProductId: string, destinationProductId: string, sizeNameMap?: Record<string, string>) => Promise<unknown>;
}

const blankSection = (productId: string, sortOrder: number): ManagedChoiceSection => ({
  productId, name: '', selectionMode: 'single', required: false, minimumSelections: 0, maximumSelections: 1,
  sortOrder, status: 'active', productSizeIds: [], values: [],
});
const blankEffect = (ingredientId: string, sortOrder: number): ManagedChoiceEffect => ({
  effectType: 'add', ingredientId, quantity: 1, sortOrder, sizeQuantities: [],
});

export function ProductChoiceSectionDialog({ product, products, sizes, ingredients, sections, onClose, onSave, onDelete, onCopy }: ProductChoiceSectionDialogProps) {
  const [selectedId, setSelectedId] = useState(sections[0]?.id ?? 'new');
  const selected = sections.find((section) => section.id === selectedId);
  const [draft, setDraft] = useState<ManagedChoiceSection>(selected ?? blankSection(product.id, sections.length * 10 + 10));
  const [sourceId, setSourceId] = useState('');
  const [mapping, setMapping] = useState<Record<string, string>>({});
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const activeSizes = sizes.filter((size) => size.productId === product.id && size.status === 'active');
  const sourceSizes = sizes.filter((size) => size.productId === sourceId && size.status === 'active');
  useEffect(() => { setDraft(selected ? structuredClone(selected) : blankSection(product.id, sections.length * 10 + 10)); setError(''); }, [product.id, sections.length, selected?.revision, selectedId]);
  useEffect(() => setMapping(Object.fromEntries(sourceSizes.map((size) => [size.id!, activeSizes.find((item) => item.name === size.name)?.id ?? '']))), [sourceId, sourceSizes.length, activeSizes.length]);
  const updateValue = (index: number, patch: Partial<ManagedChoiceSection['values'][number]>) => setDraft((current) => ({ ...current, values: current.values.map((value, valueIndex) => valueIndex === index ? { ...value, ...patch } : value) }));
  const updateEffect = (valueIndex: number, effectIndex: number, patch: Partial<ManagedChoiceEffect>) => updateValue(valueIndex, { effects: draft.values[valueIndex].effects.map((effect, index) => index === effectIndex ? { ...effect, ...patch } : effect) });
  async function save() { setSaving(true); setError(''); try { await onSave(draft); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Choice section save failed.'); } finally { setSaving(false); } }
  return <div className={styles.overlay} role="presentation"><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="choice-dialog-title">
    <header><span><small>PRODUCT CHOICES</small><h2 id="choice-dialog-title">Choices · {product.name}</h2></span><button type="button" onClick={onClose} aria-label="Close choices editor"><X size={18} /></button></header>
    <div className={styles.picker}><select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{sections.map((section) => <option key={section.id} value={section.id}>{section.name}</option>)}<option value="new">New section</option></select><button type="button" onClick={() => setSelectedId('new')}><Plus size={14} />New section</button></div>
    <div className={styles.copy}><strong>Copy choices from another product</strong><select value={sourceId} onChange={(event) => setSourceId(event.target.value)}><option value="">Choose product</option>{products.filter((item) => item.id !== product.id && item.status !== 'archived').map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      {sourceSizes.some((size) => !mapping[size.id ?? '']) ? <div className={styles.mapping}>{sourceSizes.map((size) => <label key={size.id}>{size.name}<select value={mapping[size.id ?? ''] ?? ''} onChange={(event) => setMapping((current) => ({ ...current, [size.id!]: event.target.value }))}><option value="">Map size</option>{activeSizes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>)}</div> : null}
      <button type="button" disabled={!sourceId || sourceSizes.some((size) => !mapping[size.id ?? ''])} onClick={async () => { try { await onCopy(sourceId, product.id, mapping); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Copy failed.'); } }}>Copy choices</button></div>
    <div className={styles.body}><div className={styles.fields}><label><span>Name</span><input value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} /></label><label><span>Mode</span><select value={draft.selectionMode} onChange={(event) => setDraft((current) => ({ ...current, selectionMode: event.target.value as ManagedChoiceSection['selectionMode'] }))}><option value="single">Single</option><option value="multiple">Multiple</option></select></label><label><span>Minimum</span><input type="number" min="0" value={draft.minimumSelections} onChange={(event) => setDraft((current) => ({ ...current, minimumSelections: Number(event.target.value) }))} /></label><label><span>Maximum</span><input type="number" min="1" value={draft.maximumSelections} onChange={(event) => setDraft((current) => ({ ...current, maximumSelections: Number(event.target.value) }))} /></label><label className={styles.check}><input type="checkbox" checked={draft.required} onChange={(event) => setDraft((current) => ({ ...current, required: event.target.checked, minimumSelections: event.target.checked ? Math.max(1, current.minimumSelections) : current.minimumSelections }))} />Required</label></div>
      <fieldset className={styles.sizes}><legend>Applicable sizes (empty = all)</legend>{activeSizes.map((size) => <label key={size.id}><input type="checkbox" checked={draft.productSizeIds.includes(size.id!)} onChange={() => setDraft((current) => ({ ...current, productSizeIds: current.productSizeIds.includes(size.id!) ? current.productSizeIds.filter((id) => id !== size.id) : [...current.productSizeIds, size.id!] }))} />{size.name}</label>)}</fieldset>
      <div className={styles.valuesHeader}><strong>Values</strong><button type="button" disabled={!ingredients[0]} onClick={() => setDraft((current) => ({ ...current, values: [...current.values, { name: '', priceDeltaCentimes: 0, isDefaultSelected: false, sortOrder: current.values.length * 10 + 10, status: 'active', sizeRules: [], effects: [] }] }))}><Plus size={14} />Add value</button></div>
      {draft.values.map((value, valueIndex) => <article className={styles.value} key={value.id ?? valueIndex}><div className={styles.valueFields}><label><span>Value</span><input value={value.name} onChange={(event) => updateValue(valueIndex, { name: event.target.value })} /></label><label><span>Δ MAD</span><input type="number" step="0.01" value={value.priceDeltaCentimes / 100} onChange={(event) => updateValue(valueIndex, { priceDeltaCentimes: Math.round(Number(event.target.value) * 100) })} /></label><label className={styles.check}><input type="checkbox" checked={value.isDefaultSelected} onChange={(event) => updateValue(valueIndex, { isDefaultSelected: event.target.checked })} />Default</label><button type="button" onClick={() => setDraft((current) => ({ ...current, values: current.values.filter((_, index) => index !== valueIndex) }))}><Trash size={15} /></button></div>
        <div className={styles.overrides}>{activeSizes.map((size) => { const rule = value.sizeRules.find((item) => item.productSizeId === size.id); return <label key={size.id}>{size.name}<input type="checkbox" checked={rule?.available ?? true} onChange={(event) => updateValue(valueIndex, { sizeRules: [...value.sizeRules.filter((item) => item.productSizeId !== size.id), { productSizeId: size.id!, available: event.target.checked, ...(rule?.priceDeltaCentimes === undefined ? {} : { priceDeltaCentimes: rule.priceDeltaCentimes }) }] })} /><input aria-label={`${size.name} price override`} type="number" placeholder="Δ MAD" step="0.01" value={rule?.priceDeltaCentimes === undefined ? '' : rule.priceDeltaCentimes / 100} onChange={(event) => updateValue(valueIndex, { sizeRules: [...value.sizeRules.filter((item) => item.productSizeId !== size.id), { productSizeId: size.id!, available: rule?.available ?? true, priceDeltaCentimes: Math.round(Number(event.target.value) * 100) }] })} /></label>; })}</div>
        <div className={styles.effects}>{value.effects.map((effect, effectIndex) => <div className={styles.effect} key={effect.id ?? effectIndex}><select value={effect.effectType} onChange={(event) => updateEffect(valueIndex, effectIndex, { effectType: event.target.value as ManagedChoiceEffect['effectType'] })}><option value="add">Add</option><option value="replace">Replace</option><option value="set-exact">Set exact</option><option value="remove">Remove</option></select><select value={effect.ingredientId} onChange={(event) => updateEffect(valueIndex, effectIndex, { ingredientId: event.target.value })}>{ingredients.map((ingredient) => <option key={ingredient.id} value={ingredient.id}>{ingredient.name}</option>)}</select>{effect.effectType === 'replace' ? <select value={effect.replacementIngredientId ?? ''} onChange={(event) => updateEffect(valueIndex, effectIndex, { replacementIngredientId: event.target.value })}><option value="">Replacement</option>{ingredients.map((ingredient) => <option key={ingredient.id} value={ingredient.id}>{ingredient.name}</option>)}</select> : null}<input type="number" min="0" value={effect.quantity} onChange={(event) => updateEffect(valueIndex, effectIndex, { quantity: Number(event.target.value) })} /><button type="button" onClick={() => updateValue(valueIndex, { effects: value.effects.filter((_, index) => index !== effectIndex) })}><X size={13} /></button></div>)}<button type="button" onClick={() => updateValue(valueIndex, { effects: [...value.effects, blankEffect(ingredients[0]?.id ?? '', value.effects.length * 10 + 10)] })} disabled={!ingredients[0]}><Plus size={12} />Ingredient effect</button></div>
      </article>)}</div>
    {error ? <p className={styles.error}>{error}</p> : null}<footer>{draft.id ? <button type="button" className={styles.delete} onClick={async () => { if (!draft.id || draft.revision === undefined) return; try { await onDelete({ id: draft.id, revision: draft.revision }); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Delete failed.'); } }}>Delete section</button> : <span /> }<button type="button" className={styles.save} onClick={save} disabled={saving || !draft.name.trim()}><FloppyDisk size={16} />{saving ? 'Saving…' : 'Save section'}</button></footer>
  </section></div>;
}
